const entityConfigs = {
  roles: {
    table: "roles",
    label: "Role",
    writable: ["name", "description"],
    searchable: ["name", "description"],
    filterable: ["id", "name"],
    sortable: ["id", "name", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  users: {
    table: "users",
    label: "User",
    writable: ["role_id", "full_name", "email", "phone", "password_hash", "status"],
    searchable: ["full_name", "email", "phone"],
    filterable: ["id", "role_id", "status"],
    sortable: ["id", "full_name", "email", "created_at"],
    defaultSort: "id",
    hidden: ["password_hash"],
  },
  branches: {
    table: "branches",
    label: "Branch",
    writable: ["name", "code", "address", "city", "state", "pincode", "gst_number", "phone", "email", "is_active"],
    searchable: ["name", "code", "city", "state"],
    filterable: ["id", "is_active", "city"],
    sortable: ["id", "name", "city", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  tables: {
    table: "restaurant_tables",
    label: "Table",
    writable: ["branch_id", "table_number", "seating_capacity", "area", "status"],
    searchable: ["table_number", "area", "status"],
    filterable: ["id", "branch_id", "status"],
    sortable: ["id", "table_number", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  menuCategories: {
    table: "menu_categories",
    label: "Menu category",
    writable: ["branch_id", "name", "description", "sort_order", "is_active"],
    searchable: ["name", "description"],
    filterable: ["id", "branch_id", "is_active"],
    sortable: ["id", "name", "sort_order", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  menuItems: {
    table: "menu_items",
    label: "Menu item",
    writable: ["category_id", "branch_id", "item_code", "name", "description", "price", "tax_percent", "is_veg", "is_available", "preparation_time", "image_url"],
    searchable: ["name", "item_code", "description"],
    filterable: ["id", "branch_id", "category_id", "is_available"],
    sortable: ["id", "name", "price", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  customers: {
    table: "customers",
    label: "Customer",
    writable: ["branch_id", "full_name", "phone", "email", "address", "gst_number", "customer_type"],
    searchable: ["full_name", "phone", "email"],
    filterable: ["id", "branch_id", "customer_type"],
    sortable: ["id", "full_name", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  orders: {
    table: "orders",
    label: "Order",
    writable: ["branch_id", "customer_id", "table_id", "order_no", "order_type", "order_status", "guest_count", "special_note", "subtotal", "tax_amount", "discount_amount", "grand_total", "created_by"],
    searchable: ["order_no", "order_status", "order_type"],
    filterable: ["id", "branch_id", "order_status", "order_type"],
    sortable: ["id", "order_no", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  orderItems: {
    table: "order_items",
    label: "Order item",
    writable: ["order_id", "menu_item_id", "quantity", "unit_price", "tax_percent", "item_note", "item_status", "line_total"],
    searchable: ["item_note", "item_status"],
    filterable: ["id", "order_id", "item_status"],
    sortable: ["id", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  kots: {
    table: "kots",
    label: "KOT",
    writable: ["order_id", "kot_no", "status", "kitchen_note"],
    searchable: ["kot_no", "status"],
    filterable: ["id", "order_id", "status"],
    sortable: ["id", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  invoices: {
    table: "invoices",
    label: "Invoice",
    writable: ["order_id", "invoice_no", "invoice_date", "subtotal", "tax_amount", "discount_amount", "service_charge", "grand_total", "payment_status", "gst_number", "created_by"],
    searchable: ["invoice_no", "payment_status"],
    filterable: ["id", "order_id", "payment_status"],
    sortable: ["id", "invoice_date", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  payments: {
    table: "payments",
    label: "Payment",
    writable: ["invoice_id", "payment_mode", "reference_no", "amount", "paid_at", "note"],
    searchable: ["reference_no", "payment_mode", "note"],
    filterable: ["id", "invoice_id", "payment_mode"],
    sortable: ["id", "paid_at", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  rawMaterials: {
    table: "raw_materials",
    label: "Raw material",
    writable: ["branch_id", "item_code", "name", "unit", "current_stock", "reorder_level", "last_purchase_price", "is_active"],
    searchable: ["item_code", "name", "unit"],
    filterable: ["id", "branch_id", "is_active"],
    sortable: ["id", "name", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  vendors: {
    table: "vendors",
    label: "Vendor",
    writable: ["branch_id", "name", "contact_person", "phone", "email", "address", "gst_number"],
    searchable: ["name", "contact_person", "phone", "email"],
    filterable: ["id", "branch_id"],
    sortable: ["id", "name", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  purchases: {
    table: "purchases",
    label: "Purchase",
    writable: ["branch_id", "vendor_id", "purchase_no", "purchase_date", "invoice_no", "subtotal", "tax_amount", "grand_total", "payment_status", "created_by"],
    searchable: ["purchase_no", "invoice_no", "payment_status"],
    filterable: ["id", "branch_id", "vendor_id", "payment_status"],
    sortable: ["id", "purchase_date", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  purchaseOrders: {
    table: "purchase_orders",
    label: "Purchase order",
    writable: ["branch_id", "vendor_id", "po_no", "po_date", "status", "total_amount", "note", "created_by"],
    searchable: ["po_no", "status", "note"],
    filterable: ["id", "branch_id", "vendor_id", "status"],
    sortable: ["id", "po_date", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  purchaseReturns: {
    table: "purchase_returns",
    label: "Purchase return",
    writable: ["purchase_id", "return_no", "return_date", "reason", "total_amount", "created_by"],
    searchable: ["return_no", "reason"],
    filterable: ["id", "purchase_id"],
    sortable: ["id", "return_date", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  expenseCategories: {
    table: "expense_categories",
    label: "Expense category",
    writable: ["branch_id", "name", "description"],
    searchable: ["name", "description"],
    filterable: ["id", "branch_id"],
    sortable: ["id", "name", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  expenses: {
    table: "expenses",
    label: "Expense",
    writable: ["branch_id", "category_id", "expense_date", "description", "amount", "payment_mode", "reference_no", "created_by"],
    searchable: ["description", "reference_no", "payment_mode"],
    filterable: ["id", "branch_id", "category_id", "payment_mode"],
    sortable: ["id", "expense_date", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  staff: {
    table: "staff",
    label: "Staff",
    writable: ["user_id", "branch_id", "employee_code", "designation", "joining_date", "salary", "address", "status"],
    searchable: ["employee_code", "designation", "status"],
    filterable: ["id", "branch_id", "status"],
    sortable: ["id", "employee_code", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  shifts: {
    table: "shifts",
    label: "Shift",
    writable: ["branch_id", "name", "start_time", "end_time"],
    searchable: ["name"],
    filterable: ["id", "branch_id"],
    sortable: ["id", "name", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  deliveries: {
    table: "deliveries",
    label: "Delivery",
    writable: ["order_id", "delivery_staff_id", "delivery_address", "delivery_status", "assigned_at", "delivered_at", "note"],
    searchable: ["delivery_status", "note"],
    filterable: ["id", "order_id", "delivery_staff_id", "delivery_status"],
    sortable: ["id", "assigned_at", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  deliveryStaff: {
    table: "delivery_staff",
    label: "Delivery staff",
    writable: ["branch_id", "full_name", "phone", "vehicle_number", "status"],
    searchable: ["full_name", "phone", "vehicle_number"],
    filterable: ["id", "branch_id", "status"],
    sortable: ["id", "full_name", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  stockEntries: {
    table: "stock_entries",
    label: "Stock entry",
    writable: ["branch_id", "entry_no", "vendor_id", "entry_date", "note", "created_by"],
    searchable: ["entry_no", "note"],
    filterable: ["id", "branch_id", "vendor_id"],
    sortable: ["id", "entry_date", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  stockIssues: {
    table: "stock_issues",
    label: "Stock issue",
    writable: ["branch_id", "issue_no", "issue_date", "kitchen_note", "created_by"],
    searchable: ["issue_no", "kitchen_note"],
    filterable: ["id", "branch_id"],
    sortable: ["id", "issue_date", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  stockAdjustments: {
    table: "stock_adjustments",
    label: "Stock adjustment",
    writable: ["branch_id", "raw_material_id", "adjustment_type", "quantity", "reason", "adjusted_at", "created_by"],
    searchable: ["reason", "adjustment_type"],
    filterable: ["id", "branch_id", "raw_material_id"],
    sortable: ["id", "adjusted_at", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  wastageEntries: {
    table: "wastage_entries",
    label: "Wastage entry",
    writable: ["branch_id", "raw_material_id", "quantity", "reason", "wastage_date", "created_by"],
    searchable: ["reason"],
    filterable: ["id", "branch_id", "raw_material_id"],
    sortable: ["id", "wastage_date", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
  auditLogs: {
    table: "audit_logs",
    label: "Audit log",
    writable: ["user_id", "module_name", "action_type", "record_id", "description", "ip_address"],
    searchable: ["module_name", "action_type", "description"],
    filterable: ["id", "user_id", "module_name", "action_type"],
    sortable: ["id", "created_at"],
    defaultSort: "id",
    hidden: [],
  },
};

module.exports = entityConfigs;

