export const NAV_ITEMS = [
  { key: "dashboard", label: "Dashboard", path: "/dashboard" },
  { key: "roles", label: "Roles", path: "/roles" },
  { key: "users", label: "Users", path: "/users" },
  { key: "branches", label: "Branches", path: "/branches" },
  { key: "tables", label: "Tables", path: "/tables" },
  { key: "menuCategories", label: "Menu Categories", path: "/menu-categories" },
  { key: "menuItems", label: "Menu Items", path: "/menu-items" },
  { key: "customers", label: "Customers", path: "/customers" },
  { key: "orders", label: "Orders", path: "/orders" },
  { key: "kitchen", label: "Kitchen", path: "/kitchen" },
  { key: "invoices", label: "Invoices", path: "/invoices" },
  { key: "payments", label: "Payments", path: "/payments" },
  { key: "rawMaterials", label: "Raw Materials", path: "/raw-materials" },
  { key: "vendors", label: "Vendors", path: "/vendors" },
  { key: "purchases", label: "Purchases", path: "/purchases" },
  { key: "expenses", label: "Expenses", path: "/expenses" },
  { key: "staff", label: "Staff", path: "/staff" },
  { key: "delivery", label: "Delivery", path: "/delivery" },
  { key: "reports", label: "Reports", path: "/reports" },
  { key: "settings", label: "Settings", path: "/settings" },
];

export const MODULE_CONFIGS = {
  roles: {
    title: "Role Management",
    endpoint: "/roles",
    fields: [
      { name: "name", label: "Role Name", required: true },
      { name: "description", label: "Description" },
    ],
  },
  users: {
    title: "User Management",
    endpoint: "/users",
    fields: [
      { name: "role_id", label: "Role ID", type: "number", required: true },
      { name: "full_name", label: "Full Name", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "phone", label: "Phone" },
      { name: "password", label: "Password", type: "password", required: true },
      { name: "status", label: "Status" },
    ],
  },
  branches: {
    title: "Branch Management",
    endpoint: "/branches",
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "code", label: "Code", required: true },
      { name: "city", label: "City" },
      { name: "state", label: "State" },
      { name: "phone", label: "Phone" },
      { name: "email", label: "Email", type: "email" },
      { name: "is_active", label: "Active (1/0)", type: "number" },
    ],
  },
  tables: {
    title: "Table Management",
    endpoint: "/tables",
    fields: [
      { name: "branch_id", label: "Branch ID", type: "number", required: true },
      { name: "table_number", label: "Table Number", required: true },
      { name: "seating_capacity", label: "Seats", type: "number", required: true },
      { name: "area", label: "Area" },
      { name: "status", label: "Status" },
    ],
  },
  menuCategories: {
    title: "Menu Categories",
    endpoint: "/menu-categories",
    fields: [
      { name: "branch_id", label: "Branch ID", type: "number", required: true },
      { name: "name", label: "Name", required: true },
      { name: "description", label: "Description" },
      { name: "sort_order", label: "Sort Order", type: "number" },
      { name: "is_active", label: "Active (1/0)", type: "number" },
    ],
  },
  menuItems: {
    title: "Menu Items",
    endpoint: "/menu-items",
    fields: [
      { name: "branch_id", label: "Branch ID", type: "number", required: true },
      { name: "category_id", label: "Category ID", type: "number", required: true },
      { name: "item_code", label: "Item Code", required: true },
      { name: "name", label: "Name", required: true },
      { name: "price", label: "Price", type: "number", required: true },
      { name: "tax_percent", label: "GST %", type: "number" },
      { name: "is_available", label: "Available (1/0)", type: "number" },
    ],
  },
  customers: {
    title: "Customers",
    endpoint: "/customers",
    fields: [
      { name: "branch_id", label: "Branch ID", type: "number", required: true },
      { name: "full_name", label: "Full Name", required: true },
      { name: "phone", label: "Phone", required: true },
      { name: "email", label: "Email", type: "email" },
      { name: "customer_type", label: "Type" },
    ],
  },
  orders: {
    title: "Orders",
    endpoint: "/orders",
    fields: [
      { name: "branch_id", label: "Branch ID", type: "number", required: true },
      { name: "customer_id", label: "Customer ID", type: "number" },
      { name: "table_id", label: "Table ID", type: "number" },
      { name: "order_no", label: "Order No", required: true },
      { name: "order_type", label: "Order Type" },
      { name: "order_status", label: "Status" },
      { name: "guest_count", label: "Guest Count", type: "number" },
      { name: "subtotal", label: "Subtotal", type: "number" },
      { name: "tax_amount", label: "Tax Amount", type: "number" },
      { name: "grand_total", label: "Grand Total", type: "number" },
    ],
  },
  vendors: {
    title: "Vendors",
    endpoint: "/vendors",
    fields: [
      { name: "branch_id", label: "Branch ID", type: "number", required: true },
      { name: "name", label: "Vendor Name", required: true },
      { name: "contact_person", label: "Contact Person" },
      { name: "phone", label: "Phone" },
      { name: "email", label: "Email", type: "email" },
      { name: "gst_number", label: "GST Number" },
    ],
  },
  rawMaterials: {
    title: "Raw Materials",
    endpoint: "/raw-materials",
    fields: [
      { name: "branch_id", label: "Branch ID", type: "number", required: true },
      { name: "item_code", label: "Code", required: true },
      { name: "name", label: "Name", required: true },
      { name: "unit", label: "Unit", required: true },
      { name: "current_stock", label: "Current Stock", type: "number" },
      { name: "reorder_level", label: "Reorder Level", type: "number" },
      { name: "last_purchase_price", label: "Last Purchase Price", type: "number" },
    ],
  },
  expenses: {
    title: "Expenses",
    endpoint: "/expenses",
    fields: [
      { name: "branch_id", label: "Branch ID", type: "number", required: true },
      { name: "category_id", label: "Category ID", type: "number", required: true },
      { name: "expense_date", label: "Expense Date", type: "date", required: true },
      { name: "description", label: "Description", required: true },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "payment_mode", label: "Payment Mode" },
    ],
  },
  purchases: {
    title: "Purchases",
    endpoint: "/purchases",
    fields: [
      { name: "branch_id", label: "Branch ID", type: "number", required: true },
      { name: "vendor_id", label: "Vendor ID", type: "number", required: true },
      { name: "purchase_no", label: "Purchase No", required: true },
      { name: "purchase_date", label: "Purchase Date", type: "date", required: true },
      { name: "subtotal", label: "Subtotal", type: "number", required: true },
      { name: "tax_amount", label: "Tax Amount", type: "number" },
      { name: "grand_total", label: "Grand Total", type: "number", required: true },
    ],
  },
  staff: {
    title: "Staff",
    endpoint: "/staff",
    fields: [
      { name: "user_id", label: "User ID", type: "number" },
      { name: "branch_id", label: "Branch ID", type: "number", required: true },
      { name: "employee_code", label: "Employee Code", required: true },
      { name: "designation", label: "Designation", required: true },
      { name: "salary", label: "Salary", type: "number" },
      { name: "status", label: "Status" },
    ],
  },
  delivery: {
    title: "Deliveries",
    endpoint: "/delivery",
    fields: [
      { name: "order_id", label: "Order ID", type: "number", required: true },
      { name: "delivery_staff_id", label: "Delivery Staff ID", type: "number" },
      { name: "delivery_address", label: "Address" },
      { name: "delivery_status", label: "Status" },
      { name: "note", label: "Note" },
    ],
  },
  invoices: {
    title: "Invoices",
    endpoint: "/invoices",
    fields: [
      { name: "order_id", label: "Order ID", type: "number", required: true },
      { name: "invoice_no", label: "Invoice No", required: true },
      { name: "subtotal", label: "Subtotal", type: "number", required: true },
      { name: "tax_amount", label: "Tax Amount", type: "number" },
      { name: "grand_total", label: "Grand Total", type: "number", required: true },
      { name: "payment_status", label: "Payment Status" },
    ],
  },
  payments: {
    title: "Payments",
    endpoint: "/payments",
    fields: [
      { name: "invoice_id", label: "Invoice ID", type: "number", required: true },
      { name: "payment_mode", label: "Mode", required: true },
      { name: "reference_no", label: "Reference No" },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "note", label: "Note" },
    ],
  },
};
